export default {
  login: '/',
  login2: '/login',
  forgotPassword: '/forgot-password',
  logout: '/logout',
  signup: '/signup',
  home: '/home',
  about: '/about',
  search: '/search',
  contact: '/contact',
  profile: '/profile',
  users: '/users',
  editUser: '/users/edit/:uid',
  words: '/words',
  word: '/words/:wordid',
  newWord: '/words/new',
  editWord: '/words/edit/:wordid',
  wordlists: '/wordlists',
  wordlist: '/wordlists/:wlid',
  newWordlist: '/wordlists/new',
  editWordlist: '/wordlists/edit/:wlid',
};
