name: Manual Deploy to Firebase Hosting (prod) on trigger

on:
  workflow_dispatch:
    branches:
      - main

defaults:
  run:
    working-directory: ./shabadkosh

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
      REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
      REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
      REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
      REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
      REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}

    steps:
      - uses: actions/checkout@v3
      - run: |
          # cd ./shabadkosh
          yarn install --frozen-lockfile && yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./shabadkosh
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GURMUKHI_DEV }}'
          channelId: live
          projectId: 'gurmukhi-5f8f5'
